Fix: targetAttribute added to both bower and package (Fixes #42)
cgkineo/adapt-pageNav pull request #43
Opened 2023-02-22 12:31 UTC by joe-allen-89

[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
Fixes #42 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* targetAttribute added to both bower and package (#42)

2023-06-16 11:40 UTC, StuartNicholls approved these changes

2023-06-16 11:41 UTC, StuartNicholls approved these changes

2023-06-16 12:23 UTC, kirsty-hames requested changes
`targetAttribute` needs updating in _course.schema.json_ as this is currently set as [_hotgrid](https://github.com/cgkineo/adapt-pageNav/blob/d6b335ed0b8970a3c6583b1fa3fc31dbeedb636f/schema/course.schema.json#L15) in error.

2023-06-20 21:42 UTC, swashbuck commented
> `targetAttribute` needs updating in _course.schema.json_ as this is currently set as [_hotgrid](https://github.com/cgkineo/adapt-pageNav/blob/d6b335ed0b8970a3c6583b1fa3fc31dbeedb636f/schema/course.schema.json#L15) in error.

@kirsty-hames Fixed

2023-06-21 11:04 UTC, kirsty-hames approved these changes

2023-06-21 13:59 UTC, merged